import type { ValentineConfig } from '../types';


const apologyReasons = [
  "I'm sorry for not listening when you needed me most",
  "I'm sorry for taking your love for granted",
  "I'm sorry for the times I made you feel unheard",
  "I'm sorry for not appreciating your efforts enough",
  "I'm sorry for letting my pride get in the way",
  "I'm sorry for the nights I made you cry",
  "I'm sorry for not being emotionally available",
  "I'm sorry for breaking promises I should have kept",
  "I'm sorry for not supporting your dreams fully",
  "I'm sorry for the harsh words I can't take back",
  "I'm sorry for not showing you how much you mean to me",
  "I'm sorry for making you doubt our love",
  "I'm sorry for not being the partner you deserved",
  "I'm sorry for the times I chose anger over understanding",
  "I'm sorry for not celebrating your achievements enough",
  "I'm sorry for making you feel alone in our relationship",
  "I'm sorry for not communicating my feelings better",
  "I'm sorry for the trust I broke",
  "I'm sorry for not being patient with you",
  "I'm sorry for the times I was selfish",
  "I'm sorry for not making you feel beautiful every day",
  "I'm sorry for the arguments that could have been avoided",
  "I'm sorry for not being your safe space",
  "I'm sorry for the times I disappointed you",
  "I'm sorry for not showing up when you needed me",
  "I'm sorry for making you question your worth",
  "I'm sorry for not being grateful for your presence",
  "I'm sorry for the pain I caused your heart",
  "I'm sorry for not protecting your feelings",
  "I'm sorry for the times I was inconsiderate",
  "I'm sorry for not making our relationship a priority",
  "I'm sorry for the moments I made you feel small",
  "I'm sorry for not being vulnerable with you",
  "I'm sorry for the times I was defensive instead of understanding",
  "I'm sorry for not appreciating your sacrifices",
  "I'm sorry for making you feel like you weren't enough",
  "I'm sorry for the times I was emotionally distant",
  "I'm sorry for not fighting for us harder",
  "I'm sorry for the tears you shed because of me",
  "I'm sorry for not being consistent in my love",
  "I'm sorry for the times I failed to comfort you",
  "I'm sorry for not making you feel secure",
  "I'm sorry for the promises I didn't keep",
  "I'm sorry for not being honest about my feelings",
  "I'm sorry for the times I was too stubborn to apologize",
  "I'm sorry for not making you feel like a priority",
  "I'm sorry for the moments I took you for granted",
  "I'm sorry for not being the man you fell in love with",
  "I'm sorry for letting fear control my actions",
  "I'm sorry for not showing you enough affection",
  "I'm sorry for the times I was critical instead of supportive",
  "I'm sorry for not being present in our conversations",
  "I'm sorry for making you feel like you had to change",
  "I'm sorry for not celebrating who you are",
  "I'm sorry for the times I was impatient",
  "I'm sorry for not being your biggest cheerleader",
  "I'm sorry for the moments I made you feel unloved",
  "I'm sorry for not appreciating your kindness",
  "I'm sorry for the times I was ungrateful",
  "I'm sorry for not making you laugh enough",
  "I'm sorry for the stress I added to your life",
  "I'm sorry for not being understanding of your needs",
  "I'm sorry for the times I was jealous without reason",
  "I'm sorry for not trusting you completely",
  "I'm sorry for making you feel like you had to prove your love",
  "I'm sorry for not being romantic enough",
  "I'm sorry for the times I was moody and took it out on you",
  "I'm sorry for not making you feel special every day",
  "I'm sorry for the moments I was thoughtless",
  "I'm sorry for not being grateful for your patience",
  "I'm sorry for the times I didn't stand up for you",
  "I'm sorry for not making you feel heard",
  "I'm sorry for the arguments I started unnecessarily",
  "I'm sorry for not being more considerate of your feelings",
  "I'm sorry for the times I was too proud to admit I was wrong",
  "I'm sorry for not making you feel like my queen",
  "I'm sorry for the moments I was insensitive",
  "I'm sorry for not appreciating your love language",
  "I'm sorry for the times I was distracted when you needed attention",
  "I'm sorry for not making our future plans together",
  "I'm sorry for the times I made you feel insecure",
  "I'm sorry for not being more affectionate",
  "I'm sorry for the moments I chose my ego over our love",
  "I'm sorry for not making you feel like home",
  "I'm sorry for the times I was unreliable",
  "I'm sorry for not showing you how proud I am of you",
  "I'm sorry for the moments I made you feel unimportant",
  "I'm sorry for not being more thoughtful with my words",
  "I'm sorry for the times I didn't appreciate your efforts",
  "I'm sorry for not making you feel cherished",
  "I'm sorry for the moments I was selfish with my time",
  "I'm sorry for not being more understanding of your emotions",
  "I'm sorry for the times I failed to make you smile",
  "I'm sorry for not being consistent in showing my love",
  "I'm sorry for the moments I made you doubt yourself",
  "I'm sorry for not being more supportive of your goals",
  "I'm sorry for the times I was too busy to listen",
  "I'm sorry for not making you feel like my priority",
  "I'm sorry for the moments I was ungrateful for your love",
  "I'm sorry for not being the partner who lifts you up",
  "I'm sorry for the times I made you feel alone",
  "I'm sorry for not appreciating your beautiful soul",
  "I'm sorry for the moments I was too focused on myself",
  "I'm sorry for not making you feel safe to be vulnerable",
  "I'm sorry for the times I didn't celebrate your wins",
  "I'm sorry for not being more patient with your feelings"
];

const messages = [
  {
    title: "Hey Shrutiiiiiiiiiii... 🌹",
    message: "From the moment I met you, something shifted in my universe. Your smile became my sunrise, your laugh became my favorite sound. I know I've made mistakes, but my heart has never stopped beating for you. Every single day without you has taught me something precious: how much you mean to me, how empty life feels without your presence, and how deeply I want to make things right.",
  },
  {
    title: "The Moments I Cherish 💫",
    message: "Remember our late-night conversations, Shruti? The way we could talk for hours about everything and nothing? I miss the way you understand me like no one else ever has. I miss being your person, and I miss you being mine. Those weren't just moments—they were the happiest chapters of my life. I've replayed every laugh, every inside joke, every comfortable silence in my mind a thousand times.",
  },
  {
    title: "What I've Learned 💭",
    message: "I've spent so much time reflecting on us, on me, on what went wrong. I've learned that loving someone means growing with them, not taking them for granted. I've learned that you deserve someone who shows up every single day. I want to be that person for you, Shruti—not the person I was, but the person I'm becoming for you. Time apart has given me clarity.",
  },
  {
    title: "My Deepest Truth 💕",
    message: "You're not just someone I love—you're the person I want to choose every single day for the rest of my life, Shrutiiiiiiiiiii. I want to be there for your victories and hold you through your struggles. I want to build dreams with you, laugh until we cry, and create a love story that's uniquely ours. My heart has always been yours, Shruti.",
  },
  {
    title: "A Promise From My Soul 🌟",
    message: "If you give me another chance, Shruti, I promise to love you intentionally. To communicate better. To prioritize us. To show you every day that choosing me wasn't a mistake. I'm not perfect, but I'm perfectly certain about you. I'm laying my heart completely bare here, Shrutiiiiiiiiiii. No games, no pretense—just raw, honest love.",
  },
  {
    title: "Our Shared Memories 💬",
    message: "Those midnight talks, your laugh that I made happen, every moment we shared—they're not just the past, they're the future I want, Shrutiiiiiiiiiii. I still remember exactly how it felt talking to you for the first time. Something just clicked. The way you'd smile at me across the room. Your hand in mine. Everything mattered.",
  },
  {
    title: "This Valentine's Day 💝",
    message: "I'm standing here vulnerable and hopeful, asking you to take a chance on us again, Shruti. On the love that made us both better. On the connection that nothing else has ever matched. This isn't just about romance—it's about partnership, friendship, and choosing each other through everything. Will you be mine, Shruti? 🌹",
  }
];

const noButtonTexts = [
  "Sochne do 🌹",
  "Are you absolutely sure?",
  "Really, Shruti?? 🥺",
  "Please think about us...",
  "Don't give up on us, Shrutiiiiiiiiiii 💐",
  "I'm pouring my heart out!",
  "Give me one more chance, Shruti 😰",
  "You're my everything 💔",
  "I've changed, I promise 🌹",
  "I'm literally on my knees, Shrutiiiiiiiiiii! 🙏",
  "My heart is breaking 😢",
  "Please, I'm begging you, Shruti...",
  "I can't lose you again 💔",
  "You're worth fighting for, Shrutiiiiiiiiiii! 🌟",
  "Just hear me out, Shruti 💝",
  "This could be our second chance 🌈",
  "Don't let us end like this 🥀",
  "I'm not giving up on us 💪",
  "You mean the world to me, Shrutiiiiiiiiiii 🌍",
  "Please don't walk away 🚶",
  "I'll wait forever if I have to ⏳",
  "My love for you is real, Shruti 💯",
  "Can't we try again? 🔄",
  "You're my soulmate, Shrutiiiiiiiiiii 👫",
  "I'm lost without you 🧭",
  "Give love another chance 💘",
  "I'll prove myself to you, Shruti 📝",
  "We belong together 🧩",
  "My heart only beats for you, Shrutiiiiiiiiiii 💓",
  "Please reconsider 🤔",
];

export const CONFIG: ValentineConfig = {
  colors: {
    background: "#0a0a0a",
    heartPrimary: "#ff0844",
    heartSecondary: "#ff6b9d",
    particleColor: "#ff1744",
    textGlow: "rgba(255, 8, 68, 0.8)",
  },
  text: {
    question: "Shrutiiiiiiiiiii... Will You Be My",
    valentine: "Valentine? 💝",
    yesButton: "Yes, I will! 💕",
    maybeButton: "Sochne do 🌹",
    noButtonTexts,
    successTitle: "🎉 You Just Made Me The Happiest Person Alive! 🎉",
    successMessages: [
      "I know I hurt you, and I'm truly sorry. Thank you for seeing past my mistakes, Shruti 💕",
      "I accept full responsibility for what went wrong. I promise to be the man you deserve ✨",
      "Your forgiveness means everything to me. I won't take this second chance lightly 🌹",
      "I've learned from my mistakes and I'm ready to love you the right way, Shrutiiiiiiiiiii 💖",
      "Thank you for believing in us again. I'll spend every day proving I'm worthy of your love 🙏",
    ],
    apologyReasons,
    compliments: messages.map((msg, index) => ({
      title: msg.title,
      message: msg.message,
      delay: index * 8000
    })),
  },
  animation: {
    heartbeatSpeed: 1.5,
    particleCount: 1000,
    confettiPieces: 400,
    messageDelay: 1000,
    complimentDuration: 56000,
  },
};
